/**
 * Toda string visível ao usuário mora aqui, em pt-BR.
 *
 * O código (identificadores, tabelas, commits) fica em inglês; a interface
 * fica em português. Centralizar aqui significa que trocar por next-intl
 * depois é mecânico, sem caçar texto solto em 40 componentes.
 */
export const strings = {
  app: {
    name: 'Eve Hub',
    tagline: 'Central da EveCompany',
  },

  auth: {
    signInTitle: 'Entrar no Eve Hub',
    signInSubtitle: 'Acesso restrito ao time da EveCompany.',
    email: 'E-mail',
    password: 'Senha',
    signIn: 'Entrar',
    signingIn: 'Entrando...',
    signInWithGoogle: 'Entrar com Google',
    signOut: 'Sair',
    or: 'ou',
    invalidCredentials: 'E-mail ou senha incorretos.',
    tooManyAttempts: 'Muitas tentativas. Tente de novo em alguns minutos.',
    domainNotAllowed: 'Esse e-mail não pertence ao domínio autorizado.',
    genericError: 'Não foi possível entrar. Tente de novo.',
    serviceUnavailable: 'Serviço indisponível. Verifique se o banco e o Redis estão rodando (pnpm services:up).',
    notRegistered: 'Sua conta ainda não foi criada no Eve Hub. Peça a um administrador para cadastrar o seu e-mail.',
    forgotPassword: 'Esqueci minha senha',
    forgotTitle: 'Recuperar acesso',
    forgotHint:
      'Informe o seu e-mail. Os administradores recebem o pedido e mandam para você um link para criar uma senha nova.',
    forgotSubmit: 'Pedir ajuda a um administrador',
    forgotSending: 'Enviando...',
    forgotSent:
      'Pedido enviado. Se o e-mail estiver cadastrado, um administrador vai mandar para você um link para criar uma senha nova.',
    backToSignIn: 'Voltar para o login',
    resetTitle: 'Criar uma senha nova',
    resetNewPassword: 'Senha nova',
    resetConfirm: 'Repita a senha nova',
    resetMismatch: 'As duas senhas não são iguais.',
    resetSubmit: 'Salvar senha nova',
    resetSaving: 'Salvando...',
    resetDone: 'Senha nova salva. Já pode entrar com ela.',
  },

  dock: {
    lock: 'Travar layout',
    unlock: 'Destravar layout',
    connect: 'Conectar',
    connecting: 'Conectando...',
    back: 'Voltar',
    settingsTitle: 'Configurações da dashboard',
  },

  dashboardSettings: {
    title: 'Configurações',
    backgroundTitle: 'Fundo',
    backgroundImage: 'Imagem de fundo',
    backgroundImageHint: 'Arraste uma imagem ou clique para escolher. Deixe em branco para não usar nenhuma.',
    backgroundImageDropZone: 'Arraste uma imagem aqui ou clique para escolher',
    backgroundImageUploading: 'Enviando...',
    backgroundImageRemove: 'Remover imagem',
    backgroundColor: 'Cor de fundo',
    backgroundColorHint: 'Usada por baixo da imagem (ou sozinha, se não houver imagem). Ex.: #1a1a1a.',
    interfaceTitle: 'Interface',
    uiScale: 'Escala da interface',
    uiScaleHint: 'Aumenta ou diminui o tamanho geral da interface. Padrão: 150%.',
    railFullHide: 'Esconder barra lateral por completo',
    railFullHideHint:
      'Quando ligado, a seta da barra lateral esconde ela inteira em vez de só alternar entre ícone e ícone com texto.',
    cursorFollower: 'Eve Pointer',
    cursorFollowerHint:
      'Quando ligado, um ícone da Eve acompanha o ponteiro com um leve atraso — editável com qualquer arquivo de ícone compatível (personalização completa por empresa em breve). O cursor normal do sistema continua igual nos dois casos.',
    behaviorTitle: 'Comportamento',
    liveUpdates: 'Atualizar automaticamente',
    liveUpdatesHint: 'Quando ligado, um widget recarrega sozinho assim que o dado muda. Desligado, só atualiza no "sincronizar agora".',
    defaultPage: 'Página inicial',
    defaultPageHint: 'Onde o Eve Hub abre quando você entra. O Dashboard continua a um clique no botão de início da barra lateral.',
    reset: 'Restaurar padrão',
  },

  notion: {
    token: 'Token da integração',
    tokenHint:
      'Crie em notion.so/my-integrations (Internal Integration Secret). Depois abra a database no Notion e compartilhe com a integração pelo menu "..." > Conexões.',
    database: 'URL ou ID da database',
    databaseHint: 'Pode colar a URL da página do Notion direto da barra de endereços.',
    truncated: 'Mostrando as primeiras linhas: essa database é maior que o limite de uma sincronização.',
  },

  meta: {
    pageId: 'ID da Página do Facebook',
    pageIdHint: 'O ID numérico da Página — aparece em Configurações > Sobre da própria Página.',
    igAccountId: 'ID da conta comercial do Instagram (opcional)',
    igAccountIdHint: 'Necessário só para publicar no Instagram. A conta precisa ser Business/Creator e estar vinculada a esta Página.',
    pageAccessToken: 'Token de acesso da Página',
    pageAccessTokenHint:
      'Gere um token de longa duração (idealmente via um System User no Business Suite) com as permissões pages_show_list, pages_read_engagement, pages_manage_posts, instagram_basic e instagram_content_publish.',
  },

  googleAds: {
    customerId: 'ID da conta do Google Ads',
    customerIdHint: 'Os 10 dígitos que aparecem no topo da conta, com ou sem traços (123-456-7890).',
    loginCustomerId: 'ID da conta de gerenciamento (opcional)',
    loginCustomerIdHint: 'Só quando a conta é acessada por uma conta MCC. Deixe vazio se você entra direto nela.',
    dateRange: 'Período',
    dateRangeHint: 'Intervalo que as métricas cobrem. Pode mudar depois.',
    developerToken: 'Developer token',
    developerTokenHint: 'Fica no API Center do Google Ads, na conta de gerenciamento. Precisa de acesso aprovado para ler contas reais.',
    clientId: 'OAuth client ID',
    clientIdHint: 'Do projeto no Google Cloud, em APIs e serviços > Credenciais.',
    clientSecret: 'OAuth client secret',
    clientSecretHint: 'Vem junto com o client ID, no mesmo cliente OAuth.',
    refreshToken: 'Refresh token',
    refreshTokenHint:
      'Gere com o OAuth Playground usando o escopo https://www.googleapis.com/auth/adwords e o seu próprio client ID/secret.',
  },

  profile: {
    title: 'Perfil',
    back: 'Voltar para a dashboard',
    name: 'Nome',
    email: 'E-mail',
    picture: 'Foto',
    pictureDropZone: 'Arraste uma foto aqui ou clique para escolher',
    pictureUploading: 'Enviando...',
    pictureRemove: 'Remover foto',
    edit: 'Editar dados',
    save: 'Salvar',
    cancel: 'Cancelar',
    saved: 'Dados atualizados.',
    owner: 'Owner do workspace',
    member: 'Membro',
    passwordTitle: 'Senha',
    passwordHint:
      'Senhas são guardadas com hash argon2id e não podem ser exibidas — nem por nós. Dá para trocar, não para consultar.',
    currentPassword: 'Senha atual',
    newPassword: 'Nova senha',
    showPassword: 'Mostrar senha',
    hidePassword: 'Ocultar senha',
    changePassword: 'Trocar senha',
    passwordChanged: 'Senha atualizada.',
    noPasswordYet: 'Esta conta entra só pelo Google. Defina uma senha para poder entrar por e-mail também.',
    setPassword: 'Definir senha',
  },

  team: {
    title: 'Equipe',
    add: 'Adicionar pessoa',
    confirmAdd: 'Criar conta',
    adding: 'Criando...',
    added: 'Conta criada.',
    cancel: 'Cancelar',
    name: 'Nome',
    email: 'E-mail',
    password: 'Senha inicial (opcional)',
    passwordHint: 'Deixe em branco se a pessoa vai entrar só pelo Google. Ela pode trocar depois no próprio perfil.',
    owner: 'admin',
    member: 'membro',
    socialMedia: 'Social Media',
    you: 'você',
    hasPassword: 'senha definida',
    googleOnly: 'só Google',
    disabled: 'desativado',
    disable: 'Desativar',
    enable: 'Reativar',
    remove: 'Apagar conta',
    confirmRemoveYes: 'Sim, apagar',
    removed: 'Conta apagada.',
  },

  dashboard: {
    title: 'Dashboard',
    empty: 'Nenhum widget por aqui ainda.',
    emptyHint: 'Abra a paleta com Ctrl+K e escolha "Adicionar widget".',
    addWidget: 'Adicionar widget',
    removeWidget: 'Remover widget',
    syncNow: 'Sincronizar agora',
    layoutSaved: 'Layout salvo',
  },

  nav: {
    automations: 'Automações',
    financial: 'Financeiro',
    team: 'Equipe',
    scheduling: 'Agenda',
    tables: 'Tabelas',
    jobs: 'Jobs',
    chat: 'Chat',
    connectors: 'Conectores',
  },

  rail: {
    navLabel: 'Navegação secundária',
    expand: 'Expandir menu',
    collapse: 'Recolher menu',
  },

  automations: {
    title: 'Automações',
    empty: 'Nenhuma automação registrada ainda.',
    emptyHint: 'O log de execuções do n8n vai aparecer aqui assim que o webhook estiver conectado.',
  },

  financial: {
    title: 'Financeiro',
    empty: 'Nenhum lançamento ainda.',
    emptyHint: 'Registre entradas e saídas manualmente — pode vincular a um cliente ou job.',
  },

  widget: {
    updatedAgo: (relative: string) => `atualizado ${relative}`,
    neverSynced: 'nunca sincronizado',
    syncing: 'sincronizando...',
    retry: 'Tentar de novo',
    loadError: 'Não foi possível carregar este módulo.',
    readOnly: 'somente leitura',
    crashed: 'Este widget travou e foi isolado do resto da dashboard.',
  },

  status: {
    ok: 'ok',
    syncing: 'sync',
    error: 'erro',
    disabled: 'off',
  },

  edit: {
    save: 'Salvar',
    cancel: 'Cancelar',
    edit: 'Editar',
    undo: 'Desfazer',
    undone: 'Edição desfeita.',
    savedBy: (name: string) => `editado por ${name}`,
    conflict: 'Esse dado mudou na origem depois que você abriu a tela. Recarregue antes de salvar.',
    reload: 'Recarregar',
    undoWindow: (minutes: number) => `Desfazer disponível por ${minutes} min`,
    saving: 'Salvando...',
    editHint: 'Modo de edição ligado. Altere os campos e salve.',
    pendingChanges: 'Alterações não salvas.',
    dismiss: 'Fechar aviso',
    undoLast: 'Desfazer última edição',
    alertsBottom: 'Avisos embaixo',
  },

  palette: {
    placeholder: 'Buscar módulo, ação ou cliente...',
    empty: 'Nada encontrado.',
    sectionActions: 'Ações',
    sectionNavigate: 'Ir para',
    sectionSettings: 'Configurações',
    sectionWidgets: 'Adicionar widget',
    close: 'Fechar',
    toggleTheme: 'Alternar tema claro/escuro',
    signOut: 'Sair da conta',
  },

  errors: {
    notOwner: 'Apenas um owner do workspace pode gerenciar credenciais de connector.',
    notOwnerTeam: 'Apenas um owner do workspace pode gerenciar a equipe.',
    notOwnerAutomations: 'Apenas um owner do workspace pode gerenciar o webhook de automações.',
    notOwnerFinancial: 'Apenas um owner do workspace pode gerenciar o financeiro.',
    notOwnerJobColumns: 'Apenas um owner do workspace pode definir a cor dos status.',
    notAllowedScheduling: 'Você não tem acesso à agenda.',
    unauthorized: 'Sessão expirada. Entre novamente.',
    notFound: 'Não encontrado.',
    invalidPayload: 'Requisição inválida.',
    pageCrashed: 'Essa página travou. O resto do app continua normal — tente de novo.',
    notCommentAuthor: 'Você só pode apagar seus próprios comentários.',
  },

  jobs: {
    title: 'Jobs',
    manageColumns: 'Gerenciar colunas',
    newColumn: 'Nova coluna',
    columnNamePlaceholder: 'Nome da coluna',
    newJob: 'Novo job',
    jobTitlePlaceholder: 'Título do job',
    deleteColumn: 'Apagar coluna',
    renameColumn: 'Renomear coluna',
    columnNotEmpty: (count: number) => `Essa coluna ainda tem ${count} job(s). Mova ou apague-os antes.`,
    noJobs: 'Clique no + ou Ctrl+clique para adicionar.',
    noColumns: 'Nenhuma coluna ainda.',
    dueDate: 'Prazo',
    description: 'Briefing',
    descriptionPlaceholder: 'Briefing...',
    collaborators: 'Colaboradores',
    addCollaborator: 'Adicionar colaborador',
    removeCollaborator: 'Remover',
    noCollaborators: 'Nenhum colaborador ainda.',
    pickMember: 'Escolher pessoa...',
    tasks: 'Tarefas',
    newTask: 'Nova tarefa',
    taskTitlePlaceholder: 'Título da tarefa',
    noTasks: 'Nenhuma tarefa ainda.',
    assignee: 'Responsável',
    unassigned: 'Sem responsável',
    deleteTask: 'Apagar tarefa',
    deleteJob: 'Apagar job',
    attachFile: 'Anexar arquivo',
    uploadingFile: 'Enviando arquivo...',
    removeAttachment: 'Remover anexo',
    createdBy: (name: string) => `Criado por ${name}`,
    close: 'Fechar',
    loadError: 'Não foi possível carregar o quadro de jobs.',
    retry: 'Tentar de novo',

    tabDetails: 'Detalhes',
    tabComments: 'Comentários',
    tabTimesheet: 'Timesheet',

    commentsEmpty: 'Nenhum comentário ainda. Comece a conversa.',
    commentPlaceholder: 'Escreva um comentário...',
    commentSend: 'Enviar',
    deleteComment: 'Apagar comentário',

    timesheetGeneral: 'Geral (sem tarefa)',
    timesheetStart: 'Iniciar',
    timesheetStop: 'Parar',
    timesheetRunning: 'em andamento',
    timesheetEmpty: 'Nenhum tempo registrado ainda.',
    timesheetTotal: (duration: string) => `Total: ${duration}`,
    timesheetLog: 'Registros',
    timesheetEdit: 'Editar',
    timesheetMinutesLabel: 'minutos',
    deleteEntry: 'Apagar registro',

    timerGeneralStart: 'Iniciar cronômetro geral',
    timerGeneralStop: 'Parar cronômetro geral',
    timerTaskStart: 'Iniciar cronômetro da tarefa',
    timerTaskStop: 'Parar cronômetro da tarefa',
    timerHide: 'Ocultar',
    timerRestart: 'Reiniciar cronômetro',
    timerCollapse: 'Recolher (arraste para mover)',
    timerExpand: 'Expandir (arraste para mover)',

    columnColorsTitle: 'Cor dos status',
    columnColorsHint:
      'Vale para o time todo: todo mundo vê a cor definida aqui, mas só um administrador pode mudá-la.',
    columnColorsLoadError: 'Não foi possível carregar as colunas.',
    columnColor: 'Cor',
    columnColorOpacity: 'Opacidade',
    columnBorderColor: 'Cor da borda',
    columnColorClear: 'Remover cor',
    columnColorSaving: 'Salvando...',
    columnColorSaveError: 'Não foi possível salvar a cor.',
  },

  notifications: {
    title: 'Notificações',
    empty: 'Nenhuma notificação ainda.',
    markAllRead: 'Marcar todas como lidas',
    viewAll: 'Ver todas',
  },

  chat: {
    placeholder: 'Escreva uma mensagem...',
    send: 'Enviar',
    sending: 'Enviando...',
    empty: 'Converse com o Claude — ele pode consultar seus jobs, tabelas, clientes e (se você tiver acesso) o financeiro.',
    clear: 'Limpar conversa',
    clearHint: 'Apaga o histórico deste widget. O Claude esquece o que foi dito.',
    clearConfirm: 'Apagar toda a conversa?',
    clearYes: 'Apagar',
    colorLabel: 'Cor do chat',
    colorHint: 'A cor dos balões das suas mensagens.',
    notConfigured: 'ANTHROPIC_API_KEY não configurada. Adicione a chave no .env para usar o chat.',
  },

  /** O cartão de configurações que abre no ⋮ de qualquer widget. */
  widgetSettings: {
    open: 'Configurações do widget',
    subtitle: 'Configurações do widget',
    close: 'Fechar',
    pagesLabel: 'Seções das configurações',
    pageGeneral: 'Geral',
    pageStyle: 'Estilo',
    pageConnection: 'Conexão',
    inDevelopment: 'Em desenvolvimento',
    nothingHere: 'Este módulo não tem outras opções.',
    actionsSection: 'Ações',
    lock: 'Travar posição',
    lockHint: 'Não deixa arrastar nem redimensionar este widget.',
    syncNow: 'Sincronizar agora',
    syncing: 'Sincronizando...',
    undoLast: 'Desfazer última edição',
    remove: 'Remover do painel',
    removeConfirm: 'Remover este widget do painel? Os dados dele continuam salvos.',
    removeYes: 'Remover',
    cancel: 'Cancelar',
    connectionTitle: 'Cliente e conexão',
    connectionHint:
      'Vai permitir fixar este widget em um cliente ou em uma conta conectada específica, em vez de seguir a seleção global.',
    connectionPlaceholder: 'Escolher cliente ou conta...',
  },

  view: {
    configure: 'Personalizar visualização',
    kindLabel: 'Formato',
    kindTable: 'Tabela',
    kindStatCards: 'Cartões',
    fieldsTitle: 'Campos visíveis',
    fieldsHint: 'Marque o que aparece e use as setas para mudar a ordem.',
    close: 'Fechar',
    reset: 'Mostrar todos',
    noFields: 'Nenhum campo disponível ainda — sincronize o módulo primeiro.',
  },

  notes: {
    alertsBottomHint: 'Mostra os avisos de desfazer, conflito e erro embaixo do texto, em vez de em cima.',
  },

  timer: {
    pomodoro: 'Modo Pomodoro',
    pomodoroHint: '25 minutos de foco e 5 de intervalo, encadeados. Desligado, você escolhe os minutos.',
  },

  overview: {
    sectionContent: 'O que mostrar',
    notifications: 'Notificações',
    notificationsHint: 'Notificações não lidas: jobs importantes, menções, posts que falharam.',
    agenda: 'Agenda de hoje',
    agendaHint: 'Os posts agendados para hoje.',
    nothingShown: 'Todas as seções estão ocultas. Ligue alguma nas configurações (⋮).',
  },
} as const;
